import {
    StyleSheet
} from "react-native";

const styles = StyleSheet.create({
    bgImg:{
        flex:1
    },
    navbar:{
        flexDirection:"row",
        alignItems:"center",
        backgroundColor:"transparent",
        height:50,
        width:'100%'
    },
    navHeaders:{
        color:"white",
        fontSize:18,
        fontWeight:"800",
        margin:5
    },
    navImg:{
        height:40,
        width:40,
        borderRadius:75,
        margin:5
    },
    mainContent:{
        alignItems:"center",
        margin:30
    },
    container:{
        marginBottom:10
    },
    contentHeading:{
        color:"white",
        fontSize:30,
        fontWeight:"900",
        textDecorationLine:'underline'
    },
    contentInfo:{
        color:"white",
        fontSize:16,
        fontWeight:"normal",
        marginTop:20
    },
    reactImg:{
        height:250,
        width:250,
        margin:10
    },
    fbImg:{
        height:200,
        width:200,
        margin:10
    },
    historyImg:{
        height:200,
        width:200,
        margin:15,
        borderRadius:150
    },
    modalBgImg:{
        flex:1
    },
    modalHeader:{
        fontSize:25,
        fontWeight:'900',
        margin:5,
    },
    factsContainer:{
        flexDirection:'column',
        margin:5,
        padding:10
    },
    factsHeader:{
        fontSize:18,
        fontWeight:'800',
        textDecorationLine:'underline'
    },
    factsInfo:{
        fontSize:15,
        padding:10
    },
    btnContainer:{
        margin:60
    }
});

export default styles;